### ISSUE TITLE
Deprecate ent?

### ISSUE THREAD

**Issue by mathiasbynens** [substack/node-ent#21]
There are several unresolved long-standing issues with this project. If these remain unfixed, perhaps it’s time to consider [deprecating](https://www.npmjs.org/doc/cli/npm-deprecate.html) _ent_ in favor of a competing library like _he_?

**Comment by TooTallNate** [comment]
Known issues have been fixed, and actually I like the fact that you can require the individual `encode` and `decode` functions now that they've been separated out into separate files. Gonna close this one for now.

**Comment by mathiasbynens** [comment]
:+1:

**Comment by adriaanvanrossum** [comment]
@mathiasbynens is the creator of [he](https://github.com/mathiasbynens/he), I found that funny.
