### ISSUE TITLE
bug: regexp too greedy

### ISSUE THREAD

**Issue by yetzt** [substack/node-ent#26]
the regular expression will gladly accept a numerical entity of any length (like `&#12312312;`) and then throw an exception `RangeError: Invalid code point 12312312` instead of just leaving the string alone.

**Comment by mathiasbynens** [comment]
To be clear, it shouldn't "just leave the string alone". The correct decoded result would be `"�"`.

**Comment by yetzt** [comment]
nope, everything greater than `0x10ffff` or `1114111` is not a valid unicode codepoint and can therefore not have resulted from an encoding in the the first place, so it makes no sense to try to decode it. strings that happen to match the present regular expression by chance without any intent of being interpreted as an html entity should be left untouched. i recommend limiting the hex match length to 6 hex or 7 numeric characters and checking if the integer represented is `<=0x110000`

**Comment by mathiasbynens** [comment]
@yetzt I'm saying that none of what you're proposing matches browsers. `&#12312312;` should return `"�"` as that's what browsers do. Why would you want node-ent to do something different?

Similarly, `&#x41;` and `&#x0000000000000000000041;` are equivalent; there is no reason to limit the length, as this would introduce yet another difference compared to browsers.

**Comment by yetzt** [comment]
it's ok, i'm using `he` now with `{ strict: true }`.
